version: '3.8'
services:
        cryptology:
                build:
                        context: .
                        dockerfile: Dockerfile
                tty: true
                volumes:
                        - ./:/go/src
